### ISSUE TITLE
[OpenMS-docs/main branch] Prep for 3.0.0 Pre-Release of OpenMS Documentation

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenMS/OpenMS-docs#115]
## TODOs
- [ ] https://github.com/OpenMS/OpenMS/issues/6197 @tapaswenipathak 
- [ ] https://github.com/OpenMS/OpenMS/issues/6198
- [ ] https://github.com/OpenMS/OpenMS-docs/issues/116 @jpfeuffer @timosachsenberg 
- [ ] https://github.com/OpenMS/OpenMS/issues/6110 
- [ ] https://github.com/OpenMS/pyopenms-docs/issues/284 @greengypsy 
- [ ] https://github.com/OpenMS/OpenMS-docs/issues/2 
- [ ] https://github.com/OpenMS/OpenMS-docs/issues/18 @greengypsy 
- [ ] https://github.com/OpenMS/OpenMS-docs/issues/29 @greengypsy 
- [x] https://github.com/OpenMS/OpenMS-docs/issues/56 @tapaswenipathak 
- [ ] https://github.com/OpenMS/OpenMS-docs/issues/59 @greengypsy
  - [ ] https://github.com/OpenMS/OpenMS-docs/issues/69 @greengypsy 
  - [ ] https://github.com/OpenMS/OpenMS-docs/issues/80 @jpfeuffer 
  - [ ] https://github.com/OpenMS/OpenMS-docs/issues/100 @greengypsy 
  - [ ] https://github.com/OpenMS/OpenMS-docs/issues/103 @greengypsy 
  - [ ] https://github.com/OpenMS/OpenMS-docs/issues/104 @greengypsy 
- [ ] https://github.com/OpenMS/OpenMS-docs/issues/68 
- [ ] https://github.com/OpenMS/OpenMS-docs/issues/91 
- [ ] https://github.com/OpenMS/OpenMS-docs/issues/93 @tapaswenipathak 
- [ ] https://github.com/OpenMS/OpenMS-docs/issues/94 
- [x] https://github.com/OpenMS/OpenMS-docs/issues/96 
- [ ] https://github.com/OpenMS/OpenMS-docs/issues/98 
- [ ] https://github.com/OpenMS/OpenMS-docs/issues/106 @timosachsenberg 
- [x] https://github.com/OpenMS/OpenMS-docs/issues/109 @greengypsy 
- [ ] https://github.com/OpenMS/OpenMS-docs/issues/113 @greengypsy 
- [ ] https://github.com/OpenMS/Tutorials/issues/205 @jpfeuffer @timosachsenberg

## Review Iterations
- [x] Alpha of `staging`: https://github.com/OpenMS/OpenMS-docs/pull/65: @tapaswenipathak 
- [x] https://github.com/OpenMS/OpenMS-docs/issues/4
- [x] Wiki pages archived: https://github.com/OpenMS/OpenMS/wiki @tapaswenipathak 
- [ ] Alpha of `develop`: @OpenMS/collaborators @OpenMS/core @OpenMS/developers 

## References/Documents
- [ ] https://docs.google.com/document/d/1SEDf93uXPQuYC9SXaJiu-IBD4-VkX0H88qJ5kUuJK2E/edit?disco=AAAAbJkxrYM @greengypsy @axelwalter @jpfeuffer @timosachsenberg 
- [ ] https://docs.google.com/document/d/1adohUF3ehmCzf1q_igst2js8Vyj52nL_zvm3gG3SxY8/edit @jpfeuffer

**Comment by tapaswenipathak** [comment]
cc @axelwalter @enetz @jpfeuffer @KyowonJeong @poshul @OpenMS/doc-team.
